### ISSUE TITLE
One excellent article!

### ISSUE THREAD

**Issue by ghost** [JoshData/rdfabout#3]
Thank you!  You wrote an excellent piece, Josh.  Today (early 2016), I ventured upon a great usage of DBPedia.org and limited resources left many intellectual holes unfilled/unanswered.  Your article is comprehensive and straight down the line of logical thought.  

I hope you continue to educate in whatever field you endeavor because your communication skills on technical issues are some of the best I have ever experienced.

The best to you in all you do.  And 'Thanks' again.

**Comment by JoshData** [comment]
Thank you. :-)
